### Generacion Datos Aleatorios

In [13]:
import numpy as np
np.random.seed(1234)
val=np.random.rand(15,8)
display(val.shape)
(nRows, nCols) = val.shape 
print(val)
msk_x=np.random.rand(nRows)<0.8
print(msk_x)
print(msk_y)
list_x = val[msk_x]
print(list_x)
for row in list_x:
    msk_y=np.random.rand(nCols)<0.8
    print(row[msk_y])


(15, 8)

[[0.19151945 0.62210877 0.43772774 0.78535858 0.77997581 0.27259261
  0.27646426 0.80187218]
 [0.95813935 0.87593263 0.35781727 0.50099513 0.68346294 0.71270203
  0.37025075 0.56119619]
 [0.50308317 0.01376845 0.77282662 0.88264119 0.36488598 0.61539618
  0.07538124 0.36882401]
 [0.9331401  0.65137814 0.39720258 0.78873014 0.31683612 0.56809865
  0.86912739 0.43617342]
 [0.80214764 0.14376682 0.70426097 0.70458131 0.21879211 0.92486763
  0.44214076 0.90931596]
 [0.05980922 0.18428708 0.04735528 0.67488094 0.59462478 0.53331016
  0.04332406 0.56143308]
 [0.32966845 0.50296683 0.11189432 0.60719371 0.56594464 0.00676406
  0.61744171 0.91212289]
 [0.79052413 0.99208147 0.95880176 0.79196414 0.28525096 0.62491671
  0.4780938  0.19567518]
 [0.38231745 0.05387369 0.45164841 0.98200474 0.1239427  0.1193809
  0.73852306 0.58730363]
 [0.47163253 0.10712682 0.22921857 0.89996519 0.41675354 0.53585166
  0.00620852 0.30064171]
 [0.43689317 0.612149   0.91819808 0.62573667 0.70599757 0.14983372
  0

In [43]:
val=np.random.rand(2,4)
(nRows, nCols) = val.shape 
msk_x=np.random.rand(nRows,nCols)<0.8
print(val) 
print(val[msk_x])  
val[msk_x]=0
print(val)



[[0.41977812 0.33921757 0.29714585 0.71798599]
 [0.99780718 0.55190228 0.88989605 0.16846829]]
[0.33921757 0.29714585 0.99780718 0.55190228 0.88989605 0.16846829]
[[0.41977812 0.         0.         0.71798599]
 [0.         0.         0.         0.        ]]


In [72]:
val=np.random.rand(6,4)
(nRows, nCols) = val.shape 
print(val)
msk_x=np.random.rand(nRows)<0.8
for x in val[msk_x]:    
    x[:]=0
print(val)


[[0.05620763 0.27819169 0.93671139 0.83840657]
 [0.90817385 0.59461709 0.77350132 0.34409999]
 [0.38386727 0.37794123 0.42596415 0.70689785]
 [0.24417063 0.17778136 0.21646546 0.7243904 ]
 [0.63148702 0.7945349  0.78571851 0.14497732]
 [0.08748815 0.25675692 0.64011741 0.56970789]]
[[0.05620763 0.27819169 0.93671139 0.83840657]
 [0.90817385 0.59461709 0.77350132 0.34409999]
 [0.38386727 0.37794123 0.42596415 0.70689785]
 [0.24417063 0.17778136 0.21646546 0.7243904 ]
 [0.63148702 0.7945349  0.78571851 0.14497732]
 [0.08748815 0.25675692 0.64011741 0.56970789]]


In [121]:
np.arange(0,10,2)
arr=np.arange(0,10,3)
arr=np.append(arr,110)
display(arr)
vector = np.array([[100.10, 200.42, 4.14, 89.00, 34.55, 1.12],
              [100.10, 200.42, 4.14, 89.00, 34.55, 1.12]])

selc=vector[0:2,0:2]
display(selc)
display(np.median(selc))
vector[0:2,0:2] = 0
display(vector)

array([  0,   3,   6,   9, 110])

array([[100.1 , 200.42],
       [100.1 , 200.42]])

150.26

array([[ 0.  ,  0.  ,  4.14, 89.  , 34.55,  1.12],
       [ 0.  ,  0.  ,  4.14, 89.  , 34.55,  1.12]])