In [1]:
import numpy as np

In [49]:
import networkx as nx
class Nodo:
    def __init__(self,nodo, puzzle=None,nodoshijos=None):
        self.nodo=nodo
        self.nodoPadre=None
        self.nodoshijos=nodoshijos
        self.puzzle=puzzle
    def __str__(self):
        return self.nodo
    def __eq__(self, obj):
        return (self.puzzle==obj.puzzle).all()

In [3]:
arrayI = np.array([[1,0], [3,2]])
arrayM = np.array([[1,2], [3,0]])
arrayI.shape

(2, 2)

In [4]:
def buscar_espacio_vacio(arreglo):
  for i in range(arreglo.shape[0]):
    for j in range(arreglo.shape[1]):
      if(arreglo[i,j] == 0):
        return np.array([i,j])

In [5]:
def pos_adyacente(i, j): 
  i_arriba = i - 1 
  i_abajo = i + 1  
  j_izquierda = j - 1
  j_derecha= j + 1    
  return np.array([[i_arriba,j],[i_abajo,j],[i, j_izquierda], [i, j_derecha]])

In [6]:
(i,j) = buscar_espacio_vacio(arrayI)
print(i,j)

0 1


In [7]:
pos_ayacentes = pos_adyacente(i, j)

In [8]:
pos_ayacentes
pos_ayacentes.shape

(4, 2)

In [9]:
 def crear_puzzle_hijos(i,j,pos_ayacentes,puzzle):
    puzzle_hijos= []
    fil,col = puzzle.shape
    for i_ady,j_ady in pos_ayacentes:        
        puzzle_hijo = puzzle.copy()
        val_vacio = puzzle[i,j]        
        if (0<=i_ady and i_ady<fil) and (0<=j_ady and j_ady<col):
            val_temp = puzzle[i_ady,j_ady]
            puzzle_hijo[i,j] = val_temp
            puzzle_hijo[i_ady,j_ady] = val_vacio
            puzzle_hijos.append(puzzle_hijo)            
    return puzzle_hijos        

In [10]:
puzzle_hijos = crear_puzzle_hijos(i,j,pos_ayacentes,arrayI)
print(puzzle_hijos)

[array([[1, 2],
       [3, 0]]), array([[0, 1],
       [3, 2]])]


In [11]:
puzzle = np.array([[1,0], [3,2]])
nodo = Nodo("A",puzzle)
nodo.nodoshijos=puzzle_hijos
puzzleM = np.array([[1,2], [3,0]])
nodoMeta = Nodo("G",puzzleM)

In [16]:
def crear_nodos_hijos(nodo):
    (i,j) = buscar_espacio_vacio(nodo.puzzle)
    pos_ayacentes = pos_adyacente(i, j)
    puzzle_hijos = crear_puzzle_hijos(i,j,pos_ayacentes,nodo.puzzle)
    nodos_hijos=[]
    id_nodo = "A_"
    con = 0
    for hijo in puzzle_hijos:
        id_nodo_hijo = id_nodo+str(con)
        nodos_hijos.append(Nodo(id_nodo_hijo,hijo))
        con = con+1
    return nodos_hijos

In [22]:
arrayM = np.array([[1,2], [3,0]])
arrayN = np.array([[1,2], [3,1]])
print((arrayM==arrayM).all())
print((arrayM==arrayN).all())

True
False


In [27]:
def es_nodo_meta(nodo,nodoMeta):
    return (nodo.puzzle==nodoMeta.puzzle).all()

In [29]:
nodo = Nodo("A",puzzle)
nodoMeta = Nodo("G",puzzleM)
print(es_nodo_meta(nodo,nodoMeta))
print(es_nodo_meta(nodoMeta,nodoMeta))


False
True


In [19]:
nodos_hijos = crear_nodos_hijos(nodo)
for nodohijo in nodos_hijos:
    print(nodohijo.nodo,nodohijo.puzzle)

A_0 [[1 2]
 [3 0]]
A_1 [[0 1]
 [3 2]]


In [62]:
def resolver_puzzle(nodoInicial,nodoMeta):
    nodosAbiertos=[]
    nodosVisitados=[]    
    nodosAbiertos.append(nodoInicial)  
    while nodosAbiertos:
        nodo=nodosAbiertos.pop(0)                    
        if nodo==nodoMeta:
            print('META')
            return nodo,True
        if not nodo in nodosVisitados: 
            nodosVisitados.append(nodo)            
            print(nodo.puzzle)
            nodo.nodoshijos=crear_nodos_hijos(nodo)            
            for nodohijo in nodo.nodoshijos:
                if not nodohijo in nodosVisitados:                                                         
                    if not nodohijo.nodoPadre:
                        nodohijo.nodoPadre = nodo                         
                    nodosAbiertos.append(nodohijo)
    return None, False

In [59]:
puzzle = np.array([[1,0], [3,2]])
nodo = Nodo("A",puzzle)
puzzleM = np.array([[1,2], [3,0]])
nodoMeta = Nodo("G",puzzleM)
nodoMeta,estado = resolver_puzzle(nodo,nodoMeta)
print(nodoMeta.puzzle)

[[1 0]
 [3 2]]
META
[[0 1]
 [3 2]]


In [63]:
puzzle = np.array([[2,3], [1,0]])
nodo = Nodo("A",puzzle)
puzzleM = np.array([[1,2], [3,0]])
nodoMeta = Nodo("G",puzzleM)
nodoMeta,estado = resolver_puzzle(nodo,nodoMeta)
print(nodoMeta.puzzle)

[[2 3]
 [1 0]]
[[2 0]
 [1 3]]
[[2 3]
 [0 1]]
[[0 2]
 [1 3]]
[[0 3]
 [2 1]]
[[1 2]
 [0 3]]
[[3 0]
 [2 1]]
META
[[1 2]
 [3 0]]


In [66]:
puzzle = np.array([[2,8,3], [1,6,4],[7,0,5]])
nodo = Nodo("A",puzzle)
puzzleM = np.array([[1,2,3], [8,0,4],[7,6,5]])
nodoMeta = Nodo("G",puzzleM)
nodoMeta,estado = resolver_puzzle(nodo,nodoMeta)
print(nodoMeta.puzzle)

[[2 8 3]
 [1 6 4]
 [7 0 5]]
[[2 8 3]
 [1 0 4]
 [7 6 5]]
[[2 8 3]
 [1 6 4]
 [0 7 5]]
[[2 8 3]
 [1 6 4]
 [7 5 0]]
[[2 0 3]
 [1 8 4]
 [7 6 5]]
[[2 8 3]
 [0 1 4]
 [7 6 5]]
[[2 8 3]
 [1 4 0]
 [7 6 5]]
[[2 8 3]
 [0 6 4]
 [1 7 5]]
[[2 8 3]
 [1 6 0]
 [7 5 4]]
[[0 2 3]
 [1 8 4]
 [7 6 5]]
[[2 3 0]
 [1 8 4]
 [7 6 5]]
[[0 8 3]
 [2 1 4]
 [7 6 5]]
[[2 8 3]
 [7 1 4]
 [0 6 5]]
[[2 8 0]
 [1 4 3]
 [7 6 5]]
[[2 8 3]
 [1 4 5]
 [7 6 0]]
[[0 8 3]
 [2 6 4]
 [1 7 5]]
[[2 8 3]
 [6 0 4]
 [1 7 5]]
[[2 8 0]
 [1 6 3]
 [7 5 4]]
[[2 8 3]
 [1 0 6]
 [7 5 4]]
[[1 2 3]
 [0 8 4]
 [7 6 5]]
[[2 3 4]
 [1 8 0]
 [7 6 5]]
[[8 0 3]
 [2 1 4]
 [7 6 5]]
[[2 8 3]
 [7 1 4]
 [6 0 5]]
[[2 0 8]
 [1 4 3]
 [7 6 5]]
[[2 8 3]
 [1 4 5]
 [7 0 6]]
[[8 0 3]
 [2 6 4]
 [1 7 5]]
[[2 0 3]
 [6 8 4]
 [1 7 5]]
[[2 8 3]
 [6 7 4]
 [1 0 5]]
[[2 8 3]
 [6 4 0]
 [1 7 5]]
[[2 0 8]
 [1 6 3]
 [7 5 4]]
[[2 0 3]
 [1 8 6]
 [7 5 4]]
[[2 8 3]
 [1 5 6]
 [7 0 4]]
[[2 8 3]
 [0 1 6]
 [7 5 4]]
[[1 2 3]
 [7 8 4]
 [0 6 5]]
META
[[1 2 3]
 [8 0 4]
 [7 6 5]]
